export const READY = 'READY';
export const LOGGING = 'LOGGING';
export const LOGOUTING = 'LOGOUTING';
export const UPLOADING_CATALOGUE = 'UPLOADING_CATALOGUE';
export const UPLOADING_INVOICE = 'UPLOADING_INVOICE';
export const HANDLING_CATALOGUE = 'HANDLING_CATALOGUE';
export const HANDLING_INVOICE = 'HANDLING_INVOICE';