export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';

export const CATALOG_UPLOAD_REQUEST = 'CATALOG_UPLOAD_REQUEST';
export const CATALOG_UPLOAD_SUCCESS = 'CATALOG_UPLOAD_SUCCESS';
export const CATALOG_UPLOAD_FAILURE = 'CATALOG_UPLOAD_FAILURE';

export const CATALOG_INSERT_REQUEST = 'CATALOG_INSERT_REQUEST';
export const CATALOG_INSERT_SUCCESS = 'CATALOG_INSERT_SUCCESS';
export const CATALOG_INSERT_FAILURE = 'CATALOG_INSERT_FAILURE';

export const INVOICE_UPLOAD_REQUEST = 'INVOICE_UPLOAD_REQUEST';
export const INVOICE_UPLOAD_SUCCESS = 'INVOICE_UPLOAD_SUCCESS';
export const INVOICE_UPLOAD_FAILURE = 'INVOICE_UPLOAD_FAILURE';

export const INVOICE_CALCULATE_REQUEST = 'INVOICE_CALCULATE_REQUEST';
export const INVOICE_CALCULATE_SUCCESS = 'INVOICE_CALCULATE_SUCCESS';
export const INVOICE_CALCULATE_FAILURE = 'INVOICE_CALCULATE_FAILURE';

export const INVOICE_GENERATE_RESULT_REQUEST = 'INVOICE_GENERATE_RESULT_REQUEST';
export const INVOICE_GENERATE_RESULT_SUCCESS = 'INVOICE_GENERATE_RESULT_SUCCESS';
export const INVOICE_GENERATE_RESULT_FAILURE = 'INVOICE_GENERATE_RESULT_FAILURE';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';